apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-checker
  namespace: formazione-sou
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-checker-read-only
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: deployment-checker
  namespace: formazione-sou

